# Build documentation in the docs/ directory with Sphinx
version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
   version: "3.11"
   install:
   - requirements: docs/requirements.txt
