print "\n"
print "    VoigtFit v.1.1"
print ""
print "    by Jens-Kristian Krogager"
print ""
print "    Dark Cosmology Centre"
print "    Copenhagen University"
print "    January 2015"
print ""
print "____  _           _____________"
print "    \/ \  /\_    /             "
print "        \/   \  / oigtFit      "
print "              \/               "
print ""
print ""
from VoigtFit import *
